### ISSUE TITLE
Support of other http methods like PUT and PATCH

### ISSUE THREAD

**Issue by evandor** [itinken/jinplace#3]
If I am not mistaken, jinplace always posts its data, but quite often PUTing or PATCHing make more sense, e.g. when updating an existing text.

**Comment by dabaer** [comment]
The RFC defines PUT and PATCH for exactly the thing this plugin is designed for. Additionally, I can't think of a use case where POST would be appropriate off the top of my head.

**Comment by itinken** [comment]
Merged pull req from @dabaer which implements this request.  Thanks!
